name: shopping_cart
description: A new Dart project.
version: 1.0.0
environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  http: ^0.13.3




dev_dependencies:
  # Testing dependencies (optional for your case)
  pedantic: ^1.11.0
